---
- name: Installing nginx
  hosts: all
  become: true
  tasks:
    - name: Installation
      package:
        name: nginx
        state: present
        update_cache: true
    - name: Running
      service:
        name: nginx
        enabled: true
...
