---
- name: Installing nginx
  hosts: all
  become: true
  tasks:

    - name: Updating state
      yum:
        update_cache: true

    - name: Installation
      yum:
        name: nginx
        state: present
        
    - name: Running
      service:
        name: nginx
        enabled: true
        state: started
