---
- name: Updating the systems
  hosts: all
  become: true
  tasks:

    - name: Updating
      tags: update
      package:
        update_cache: yes
      changed_when: true

- name: Adding an ssh public key
  hosts: all
  become: yes
  roles:
    - base 

- name: Installing nginx in the host
  hosts: all
  become: true
  roles:
    - web_servers

- name: Installing Terraform
  hosts: main_host
  become: yes
  roles:
    - main_host 

- name: Data_base
  hosts: all
  become: true
  roles:
    - db_servers

- name: File
  hosts: all
  become: yes
  roles:
    - file_servers

      
...
