- name: Installing Apache2                                                                                
  tags: apache, localhost                                                                                
  package:                                                                                              
    name: "{{apache_package_name}}"                                                                                         
    state: latest                                                                                       
                                                                                                            
- name: Enabling and running the apache server
  service:
    name: "{{apache_service}}"
    enabled: yes
    state: started

- name: Copy the text
  copy:
    src: message.html
    dest: /var/www/html/index.html

